name: Node CLI Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

          cache-dependency-path: task/package.json

      - name: Install dependencies

        working-directory: task
        run: npm ci

      - name: Run linter and tests

        working-directory: task
        run: npm test
